### ISSUE TITLE
Aria Labels for settings pop

### ISSUE THREAD

**Issue by StuartNicholls** [cgkineo/adapt-visua11y#22]
Aria labels are required on the following items to prevent them being read out by aa screen reader.

Preview:
Title & para drop cap.

Options:
All icons

Additionally some of the options aren't being read out.

**Comment by oliverfoster** [comment]
fixed in https://github.com/cgkineo/adapt-visua11y/commit/5dc4cdab797d823e7c862948eaeacf8b203c59c8
