### ISSUE TITLE
Applying tranform to .page can break fixed-position elements

### ISSUE THREAD

**Issue by swashbuck** [cgkineo/adapt-visua11y#33]
https://github.com/cgkineo/adapt-visua11y/blob/91e51ab813deebc9978a1b28411255aadd37ee3b/less/modifiers.less#L78

The .page div is using transform: translateZ(0px).  Any fixed-position element that's inside of .page will now be positioned relative to .page rather than the viewport since applying a transform creates a new stacking context.  https://www.darrenlester.com/blog/why-fixed-position-element-not-relative-to-viewport

For example, in Scrollsnap 3.1.4 (not sure about the latest version), the Scrollsnap button bar is using position: fixed and bottom: 0 to put it at the bottom of the browser window.  This button bar lives inside of the .page div.  Once a block is unlocked, the .page div naturally expands in height to show the next block.  This causes the button bar that should be docked to the bottom of the browser window to now be docked further down and offscreen since bottom: 0 is relative to .page and not the viewport.  I've also had this issue with trying to show a fixed position Trickle bar at the bottom of the window.

There is a comment in the .less that the transform is "for older browsers."  Is this still needed?  Which older browsers need this style?  Is it possible to remove this style without breaking overall functionality?

**Comment by oliverfoster** [comment]
ie11, please remove if you need

**Comment by swashbuck** [comment]
Actually, it looks like the 'filter' style also creates a new stacking context ( https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context ).  So, I think the solution is to modify _other_ plugins as needed (ex. Scrollsnap, Trickle), moving the DOM elements outside of div.page (which uses 'filter').

Closing this ticket.

**Comment by oliverfoster** [comment]
I don't understand why the page div has filter applied to it. It shouldn't. They're very specified styles.

**Comment by oliverfoster** [comment]
Oh no, it kind of is, but also not. The theme applies background images to major divs, which it shouldn't do. It should really be injecting minor divs onto which background images should be applied such that these filters don't conflict in the way you've described. It's more of a theme issue than a visua11y issue, unfortunately.
