### ISSUE TITLE
Accessibility settings enabled by default  (Even in incognito window and from different urls)

### ISSUE THREAD

**Issue by RMurray89** [cgkineo/adapt-visua11y#40]
Hi,

When I preview a course from the authoring tool with the plugin enabled, even in an incognito window all the settings appear to be applied by default when the course loads.

The modal looks like this:

![image](https://user-images.githubusercontent.com/3612643/175326321-54047c48-9e06-480f-9bb8-5a8302e68650.png)

As you can see multiple colour shifts are happening because multiple options are checked by default.

There is an issue appearinng when I inspect with browser tools

![image](https://user-images.githubusercontent.com/3612643/175326793-5da02335-0013-46f4-aca1-260f2f00f3d5.png)

It's receiving a string it's not expecting rather than a boolean value.

**Comment by simondate** [comment]
@RMurray89 , I've just created a PR for this. Can you test it here when you get a chance? https://github.com/simondate/adapt-visua11y/tree/issue/41

**Comment by RMurray89** [comment]
Hi @simondate - Sorry I've been on annual leave. I just gave this a test this morning, and it's working well. I noticed there is now a checkbox in settings - 'Enabled on course load' for each setting which is a great solution. The only issue I've noted is that the notify title and body text appears below the visua11y settings. 

You can see this in the HTML - 
![image](https://user-images.githubusercontent.com/3612643/182569686-84a3866c-a037-49e7-b11d-6d43980f5f8c.png)

It would be great if this text appeared inside the visua11y div, at the top before the first settings group. At the moment the text is black (I can probably fix this the theme) - against the black transparent overlay when the modal opens so it is difficult to see.

**Comment by oliverfoster** [comment]
@RMurray89 https://github.com/cgkineo/adapt-visua11y/pull/46
