### ISSUE TITLE
Sole use of color to convey selection

### ISSUE THREAD

**Issue by swashbuck** [cgkineo/adapt-visua11y#41]
## Bug Description:
Readability radio options in the accessibility dialog rely on a background color change alone to indicate selection of a radio item. For users with low vision or color blindness, this change may not be perceivable.

## Steps to Reproduce:

1. Using a keyboard, activate the "Accessibility" button in the header.
2. Navigate to the readability section and note the difference in presentation between the selected options and unselected options. 

## Actual Behavior:

Selected options are presented with black text on a gray background, while unselected options are presented with black text on a white background.

## Expected Behavior:

Provide a non-color dependent visual indicator of selection, for example and underline to ensure clear and consistent identification of the selected option for all users.

![readability](https://user-images.githubusercontent.com/898168/177416639-91cbd586-ceac-474d-b038-0dcb08a0aeec.jpg)

**Comment by swashbuck** [comment]
@oliverfoster Will you assign this ticket to me?  I don't have permission.

**Comment by oliverfoster** [comment]
> @oliverfoster Will you assign this ticket to me? I don't have permission.

try again
