### ISSUE TITLE
Add support for tooltip API

### ISSUE THREAD

**Issue by kirsty-hames** [cgkineo/adapt-visua11y#52]
For consistency with other navigation buttons when tooltips are enabled, Visua11y should support the Core tooltip API https://github.com/adaptlearning/adapt-contrib-core/pull/207

Note, Visua11y does already include a [tooltip](https://github.com/cgkineo/adapt-visua11y/blob/master/templates/visua11yButton.hbs) which also acts as the button aria-label but I think it makes sense to align this with other navigation buttons for consistency unless there's good reason for this to remain as is? I've already had to implement this on a project so it just needs tidying up.

**Comment by oliverfoster** [comment]
Yes

**Comment by kirsty-hames** [comment]
I'm certain I've implemented this on a project since and I just need to commit this back - I'll pick up during the week.
