### ISSUE TITLE
Hover state sticking when nav button selected

### ISSUE THREAD

**Issue by kirsty-hames** [cgkineo/adapt-visua11y#6]
I've had this issue reported on a project and I've been able to replicate elsewhere. 

When selecting the nav button `.visua11y-btn` to open the visua11y settings, the hover state remains on the button until you hover over the button again.

The hover state itself is inherited from the generic nav button class `.nav__btn` which styles are set in Vanilla's nav.less - the issue only occurs for this button however....

**Comment by StuartNicholls** [comment]
This only seems to occur if you click on the div.icon or the pseudo element within that. Clicking on the button border seems to work as expected

**Comment by oliverfoster** [comment]
It's an odd hover bug in chrome where by hovering on the inner span and clicking, introducing the popup, means the hover state doesn't disappear. Can't fix. :(
