### ISSUE TITLE
Visua11y / PLP line-height conflict

### ISSUE THREAD

**Issue by guywillis** [cgkineo/adapt-visua11y#60]
The line height manipulation within the visua11y plugin is causing a conflict with the PLP navigation btn.

The PLP plugin has a [style](https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/blob/master/less/pageLevelProgress.less#L6) that sets the line height of the PLP nav button to 0. This style is required to ensure the height of the parent container matches that of its children.

When installed and enabled, the visually plugin is overriding this line height value and setting it equal to the [default](https://github.com/cgkineo/adapt-visua11y/blob/master/example.json#L85) set in course json. This default, presumably, is required for the main body text so can't be removed. 

If a style is added to the build to force the line height to 0 `line-height: 0 !important;`, this value is subsequently overridden and changed to 1.

**Comment by kirsty-hames** [comment]
Can this be closed now @guywillis?

**Comment by guywillis** [comment]
Not quite yet, there's still open PR - I can close this when that PR has been merged

**Comment by guywillis** [comment]
@kirsty-hames Yup!

**Comment by StuartNicholls** [comment]
Fixed here: https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/156
