### ISSUE TITLE
cookie storage rules

### ISSUE THREAD

**Issue by danielghost** [cgkineo/adapt-visua11y#7]
Is there a potential issue with storing the selections in a cookie without informing users or at least making the client aware?
Not all Adapt content is built for internal client use, so not sure if this impacts the decision on whether cookies can be used without agreement. There isn't any personal data stored but not sure on the rules for The Cookie Law.

Could the data be saved to via `Adapt.offlineStorage` for use with SCORM or xAPI, or does it take up too much space for SCORM `cmi.suspend_data`?

**Comment by oliverfoster** [comment]
https://wikis.ec.europa.eu/display/WEBGUIDE/04.+Cookies+and+similar+technologies
