### ISSUE TITLE
text-shadow + box-shadow support

### ISSUE THREAD

**Issue by oliverfoster** [cgkineo/adapt-visua11y#73]
### Subject of the issue
Add support for text-shadow and box-shadow

**Comment by kirsty-hames** [comment]
Hey @oliverfoster, just to check I've understood the issue, are you suggesting a config option to remove text-shadow and box-shadow? 

Currently, enabling 'No Transparency' removes [box-shadow](https://github.com/cgkineo/adapt-visua11y/blob/f952a6516e1ecaa2ad1ccdea544d3cd6a4299469/js/CSSRuleModifiers.js#L20). None of the existing config options impact text-shadow. For consistency, 'No Transparency' should probably remove text-shadow too?

**Comment by oliverfoster** [comment]
Honestly @kirsty-hames I have no idea what it was that I meant when I wrote this ticket. So....

Let's say that I meant only to remove it with 'no transparency' and not to modify the colours.... for the moment... as the colour definitions can become quite complicated with multiple text/box shadows:
```css
text-shadow: 1px 1px 2px red, 0 0 1em blue, 0 0 0.2em blue;
box-shadow: 3px 3px red, -1em 0 .4em olive;
```

In order to hide text-shadows with no transparency, just duplicate https://github.com/cgkineo/adapt-visua11y/blob/f952a6516e1ecaa2ad1ccdea544d3cd6a4299469/js/CSSRuleModifiers.js#L19-L27 these lines and change the property name.

**Comment by kirsty-hames** [comment]
I'd argue in instances where `box-shadow` has a zero offset and blur, we don't need to remove this. A `box-shadow` with a zero offset and blur displays as a solid border (no transparency). Quite often `box-shadow` is used in favour of `border` or `outline` as it offers more flexibility styling - although keen to get other opinions on this. I find it renders decimal values more crisp/consistent across browsers/devices. 

I was thinking something like this for checking offset and blur:
```
    // Remove box shadows with transparency
    'box-shadow',
    null,
    function (output) {
      if (!this.noTransparency) return;
      const zeroOffsetAndBlur = '0px 0px 0px';

      if (!output.includes(zeroOffsetAndBlur) ) {
        return 'none';
      }
    }
```
And on another note, there are instances in Adapt where `box-shadow` is used and removing this does impact the display, making elements or their state less legible. See examples below. It would probably make sense to raise these as separate issues for the plugin/Vanilla to provide an alternative style or fallback.

Resources selected tab:
<img width="336" alt="resources_tab_selected" src="https://github.com/cgkineo/adapt-visua11y/assets/7045330/07f97d9d-85bc-4bb6-b600-d2b33ffe9676">
<img width="328" alt="resources_tab_selected_bs_removed" src="https://github.com/cgkineo/adapt-visua11y/assets/7045330/12441cfc-64d6-429e-b86a-42792802c15f">
<br>
Slider thumb:
<img width="152" alt="slider_thumb" src="https://github.com/cgkineo/adapt-visua11y/assets/7045330/eaa00226-1c83-4903-96a3-7f4f503e0ff0">
<img width="125" alt="slider_thumb_bs_removed" src="https://github.com/cgkineo/adapt-visua11y/assets/7045330/8b5769bb-8c5c-416b-b64c-7622febc5362">
Media play icon (less of an issue as the icon is visible):
<img width="128" alt="media_play_btn" src="https://github.com/cgkineo/adapt-visua11y/assets/7045330/7a2bfd8c-99a5-4bdc-b216-8f2e64311fa0">
<img width="123" alt="media_play_btn_bs_removed" src="https://github.com/cgkineo/adapt-visua11y/assets/7045330/3f213a66-b9b2-4fc4-b499-b4c365238e2d">
<br>

**Comment by oliverfoster** [comment]
Yup, makes sense. remember return earlies.

```js
    // Remove box shadows with transparency
    'box-shadow',
    null,
    function (output) {
      if (!this.noTransparency) return;
      const zeroOffsetAndBlur = '0px 0px 0px';
      if (output.includes(zeroOffsetAndBlur) ) return;
      return 'none';
    }
```
