### ISSUE TITLE
Consider changing 'no background images' to 'hide decorative images'

### ISSUE THREAD

**Issue by guywillis** [cgkineo/adapt-visua11y#74]
### Subject of the issue
The checkbox 'no background images' is rather confusing as it refers more to decorative imagery rather than exclusively background imagery (in HTML terms).

### Your environment
* Master

### Expected behaviour
Change 'no background images' checkbox title to 'hide decorative images'

**Comment by swashbuck** [comment]
My only concern is that sometimes non-background images (ex. Graphic components) are often used as decorative imagery, too. Visua11y's setting would presumably not disable these images, so it might be confusing?

**Comment by oliverfoster** [comment]
All images without alt/aria are hidden. This should include decorative graphics.

**Comment by swashbuck** [comment]
> All images without alt/aria are hidden. This should include decorative graphics.

Ah, got it. I'm on board with this change then. 👍
