### ISSUE TITLE
CSS inherit

### ISSUE THREAD

**Issue by StuartNicholls** [cgkineo/adapt-visua11y#77]
Visua11y seems to be nescient of css inherit. So colours inherited from higher up the tree will be overwritten with colours in selectors set on that node. Especially problematic if visua11y is installed at a later date.

It maybe that we just need to set colours explicitly and avoid using inherit altogether if this adds too much complexity to the processing.

**Comment by oliverfoster** [comment]
Can I have some examples of what you're seeing please? The issue is a bit abstract.

**Comment by oliverfoster** [comment]
Cool. I can fix that.

**Comment by oliverfoster** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/computed_value
