### ISSUE TITLE
Align with other navigation buttons for consistency

### ISSUE THREAD

**Issue by kirsty-hames** [cgkineo/adapt-visua11y#92]
### Subject of the issue
As noted in #52, Visua11y navigation button is inconsistent with other navigation buttons and could do with the following amends:
- prefix `.visua11y-btn` class with `.nav__` e.g `.nav__visua11y-btn`
- apply `aria-hidden="true"` to the [`.icon`](https://github.com/cgkineo/adapt-visua11y/blob/1e73652688812bbfdbc7c02cbcecfe8594e5e367/templates/visua11yButton.hbs#L4)
- replace the [tooltip](https://github.com/cgkineo/adapt-visua11y/blob/1e73652688812bbfdbc7c02cbcecfe8594e5e367/templates/visua11yButton.hbs#L1) with `<button>` level `aria-label`.

**Comment by swashbuck** [comment]
Hi, @kirsty-hames . It would be good to convert the template to JSX as well since the other two Visua11y templates are already JSX. Happy to help out with this while I work on #90 , so just let me know.

**Comment by swashbuck** [comment]
Thanks, @kirsty-hames . I went ahead and created the JSX template in #93 (still in draft). I've taken care of the first two bullets, but I will need to do this one:

"replace the [tooltip](https://github.com/cgkineo/adapt-visua11y/blob/1e73652688812bbfdbc7c02cbcecfe8594e5e367/templates/visua11yButton.hbs#L1) with <button> level aria-label."

**Comment by kirsty-hames** [comment]
> Thanks, @kirsty-hames . I went ahead and created the JSX template in #93 (still in draft). I've taken care of the first two bullets, but I will need to do this one:
> 
> "replace the [tooltip](https://github.com/cgkineo/adapt-visua11y/blob/1e73652688812bbfdbc7c02cbcecfe8594e5e367/templates/visua11yButton.hbs#L1) with level aria-label."

It's looking good thanks @swashbuck. I'll do a proper review when you're done with #93.

**Comment by swashbuck** [comment]
@kirsty-hames These changes are ready for review in #93
