### ISSUE TITLE
Adapt CLI install/devinstall issues

### ISSUE THREAD

**Issue by swashbuck** [cgkineo/adapt-visua11y#97]
### Subject of the issue
I cannot successfully install Visua11y using `adapt install` or `adapt devinstall`. This happens when using either `visua11y` or `adapt-visua11y` as the target plugin.

### Your environment

* Adapt Framework v5.31.21
* Adapt CLI v3.0.11

### Steps to reproduce

1. Run `adapt install adapt-visua11y`

<img width="450" alt="Screenshot 2023-08-09 at 9 15 38 AM" src="https://github.com/cgkineo/adapt-visua11y/assets/898168/1049907a-34a1-48cf-95e4-d0d7ca8f998a">

2. Select the `master` branch to install

### Expected behaviour
Visua11y should be installed.

### Actual behaviour
Visua11y is not installed.

```
Installing plugins 100% completeTypeError: Cannot read properties of null (reading 'component')

at file:///Users/xxxxxx/.nvm/versions/node/v18.16.0/lib/node_modules/adapt-cli/lib/integration/Plugin.js:331:62
at Array.find (<anonymous>)
at Target.getType (file:///Users/xxxxxx/.nvm/versions/node/v18.16.0/lib/node_modules/adapt-cli/lib/integration/Plugin.js:331:45)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Target.getTypeFolder (file:///Users/xxxxxx/.nvm/versions/node/v18.16.0/lib/node_modules/adapt-cli/lib/integration/Plugin.js:342:18)
at async Target.install (file:///Users/xxxxxx/.nvm/versions/node/v18.16.0/lib/node_modules/adapt-cli/lib/integration/Target.js:161:30)
```

**Comment by swashbuck** [comment]
@oliverfoster Apparently, this plugin is not registered. When I try to register it, I get this error from Adapt CLI (_register()_ in _lib/integration/PluginManagement/register.js_):

> Error: The package you are trying to register is marked as private

Should I change `private` to 'false' in `bower.json` and `package.json`?

**Comment by oliverfoster** [comment]
Please definitely **do not** change the private value. That would cause the plugin to be registered on npm by the github release automation.

**Comment by swashbuck** [comment]
Changing it to `"private": false` locally didn't help. I believe it's looking at the _bower.json_ that's on the master branch (or possibly the latest tag or release) in the GitHub repo rather than what I have locally.

> That would cause the plugin to be registered on npm by the github release automation.

@oliverfoster Since this isn't a private Kineo plugin, don't we want it to be registered on npm? Since it's public?

**Comment by swashbuck** [comment]
In bower's _register.js_:

```
        // Attempt to resolve the package referenced by the URL to ensure
        // everything is ok before registering
        repository = new PackageRepository(config, logger);
        return repository.fetch({ name: name, source: url, target: '*' });
    })
        .spread(function(canonicalDir, pkgMeta) {
            if (pkgMeta.private) {
                throw createError(
                    'The package you are trying to register is marked as private',
                    'EPRIV'
                );
            }
```

**Comment by swashbuck** [comment]
@oliverfoster Ok, thanks for clearing that up.

Would the solution here be to temporarily change `private` to 'true' in the repo, register the plugin via adapt-cli, and then change it back to 'false'?

**Comment by oliverfoster** [comment]
I'm pondering on a possible, easy solution. Give me some time to think about it.

**Comment by swashbuck** [comment]
Ok, thanks. In the meantime, I've created a linked PR to add the repo details.

**Comment by oliverfoster** [comment]
Please approve both of these @swashbuck 
https://github.com/adaptlearning/adapt-cli/pull/199
https://github.com/adaptlearning/adapt-cli/pull/201

**Comment by swashbuck** [comment]
Approved 👍

**Comment by swashbuck** [comment]
@oliverfoster Closing this ticket as the two related tickets have now been merged.

https://github.com/adaptlearning/adapt-cli/pull/199
https://github.com/adaptlearning/adapt-cli/pull/201
